@baseUrl = http://localhost:8080/v1
@authtoken = {{create_session.response.body.accessToken}}

# @name sign_up
POST {{baseUrl}}/users/sign-up
Content-Type: application/json

{
  "name": "John Doe Crawford",
  "email": "mrjohndoe996@gmail.com",
  "password": "1234"
}

###

# @name confirm_email
POST {{baseUrl}}/users/confirm-email/e207f493-2580-4b8f-bc38-4b57414e0370
Content-Type: application/json

###

# @name create_session
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "mrjohndoe996@gmail.com",
  "password": "123456"
}

###

# @name create_public_key
POST {{baseUrl}}/public-key
Content-Type: application/json
Authorization: Bearer {{authtoken}}

{
  "secretKeyValue": "secret_31TnEfXmRXhvUEYqZRSjdqwXswgxiPAMHBqydpuS2sh",
  "databaseId": "e47ad2baa2fb4bae9ffc8132cd41ff92"
}

###

# @name query_notion_database
POST {{baseUrl}}/notion/database/query
Content-Type: application/json

{
  "publicKey": "public_cbec1b9e-6606-4be2-88ad-efb195f8aa7f",
  "query": {
    "property": "published",
    "checkbox": {
      "equals": true
    }
  }
}

###

# @name resend_email_confirmation
POST {{baseUrl}}/users/resend/email-confirmation
Content-Type: application/json

{
  "publicId": "e3665944-a8d7-40c1-a39c-97dc4a3d0c89"
}

###

# @name list_public_keys
GET {{baseUrl}}/public-keys
Content-Type: application/json
Authorization: Bearer {{authtoken}}

###

# @name delete_public_key
DELETE {{baseUrl}}/public-keys/d37aa862-b105-4f1c-afed-8105c1660ac5/delete
Content-Type: application/json
Authorization: Bearer {{authtoken}}
