@baseUrl = http://localhost:8080/v1
@authtoken = {{create_session.response.body.accessToken}}

# @name sign_up
POST {{baseUrl}}/users/sign-up
Content-Type: application/json

{
  "name": "John Doe Crawford",
  "email": "",
  "password": "1234"
}

###

# @name confirm_email
POST {{baseUrl}}/users/confirm-email/e207f493-2580-4b8f-bc38-4b57414e0370
Content-Type: application/json

###

# @name create_session
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "1234"
}

###

# @name create_public_key
POST {{baseUrl}}/public-key
Content-Type: application/json
Authorization: Bearer {{authtoken}}

{
  "secretKeyValue": "",
  "databaseId": ""
}

###

# @name query_notion_database
POST {{baseUrl}}/notion/database/query
Content-Type: application/json

{
  "publicKey": "public_1773b718-7239-49ba-beb1-b2eec45f9f49"
}